name: CI/CD
on:
  push:
    branches:
      - TS_ci
  pull_request:
    branches:
      - TS_ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build site
      run: yarn install && yarn build && yarn generate
    - name: Deploy site to AWS
      run: ./scripts/deploy.sh
